seed: 42
device: cuda

data:
  train_csv: /data/train.csv
  val_csv: /data/val.csv
  test_csv: /data/test.csv
  target_spacing: [1.5, 1.5, 1.5]  # z, y, x in mm
  patch_size: [128, 160, 160]
  augment: true

model:
  in_channels: 3            # ct + tumor + optional probe (set to 2 if no probe)
  out_channels: 1
  base_channels: 32
  depth: 4

train:
  batch_size: 1
  num_workers: 4
  max_epochs: 200
  lr: 2.0e-4
  weight_decay: 1.0e-5
  mixed_precision: true
  save_dir: runs/unet

loss:
  dice_weight: 1.0
  bce_weight: 1.0

inference:
  threshold: 0.5
